# -*- coding: utf-8 -*-
"""rock_paper_scissors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VsesElnxQ33Q1Tm9PseogflP5W1bRBbG
"""

import random as rn

def computer_choice():
    return rn.choice(['rock', 'paper', 'scissors'])

def user_choice():
    your_choice = input("Enter your choice (rock, paper, scissors): ").strip().lower()
    while your_choice not in ['rock', 'paper', 'scissors']:
        print("Invalid choice. Please choose rock, paper, or scissors.")
        your_choice = input("Enter your choice (rock, paper, scissors): ").strip().lower()
    return your_choice

def determine_winner(user, computer):
    if user == computer:
        return "tie"
    elif (user == 'rock' and computer == 'scissors') or \
         (user == 'scissors' and computer == 'paper') or \
         (user == 'paper' and computer == 'rock'):
        return "win"
    else:
        return "lose"

def display_result(user, computer, result):
    print(f"You have chosen: {user}")
    print(f"Computer has chosen: {computer}")
    if result == "tie":
        print("Match tie!")
    elif result == "win":
        print("You win!")
    else:
        print("You lose!")

def game():
    your_score = 0
    computer_score = 0
    while True:
        your_choice = user_choice()
        computer_choice_result = computer_choice()
        game_result = determine_winner(your_choice, computer_choice_result)
        display_result(your_choice, computer_choice_result, game_result)

        if game_result == "win":
            your_score += 1
        elif game_result == "lose":
            computer_score += 1

        print(f"Score - You: {your_score}, Computer: {computer_score}")

        play_again = input("Do you want to play again? (yes/no): ").strip().lower()
        if play_again != 'yes':
            break

    print("Thanks for playing!")

if __name__ == "__main__":
    game()